events {}

http {
    # Mapear la cookie "entorno" a los backends correspondientes
    map $cookie_entorno $backend_activo {
        green   green:8000;
        default blue:8000;
    }

    map $cookie_entorno $nombre_entorno {
        green   "green";
        default "blue";
    }

    server {
        listen 80;
        resolver 127.0.0.11 valid=10s;


        add_header X-Entorno-Activo $nombre_entorno always;

        location = /usar-green {
            add_header Set-Cookie "entorno=green; Path=/; Max-Age=86400";
            return 302 $scheme://$http_host/;
        }

        location = /usar-blue {
            add_header Set-Cookie "entorno=blue; Path=/; Max-Age=86400";
            return 302 $scheme://$http_host/;
        }

        location / {
            proxy_pass http://$backend_activo$request_uri;           
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws/ {
            proxy_pass http://$backend_activo$request_uri;            
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}